FROM openjdk:11.0.1-jdk-oracle
MAINTAINER  irina butakova allegr12@gmail.com
COPY target/math-expression-evaluator-0.0.1-SNAPSHOT.jar math-expression-evaluator.jar
CMD ["java", "-jar", "math-expression-evaluator.jar"]
